ERROR 2025-10-13 12:51:04,333 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 12:51:04,336 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 12:51:08,663 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 12:51:08,664 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 12:51:08,666 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 12:51:08,671 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 12:51:09,465 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 12:51:09,465 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 12:51:09,470 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 12:51:09,476 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 12:51:47,119 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 12:51:47,121 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 12:51:47,125 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 12:51:47,126 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 12:51:48,000 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 12:51:48,003 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 12:51:48,005 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 12:51:48,006 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 12:51:48,372 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 12:51:48,372 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 12:51:48,382 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 12:51:48,384 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 12:51:48,591 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 12:51:48,594 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 12:51:48,596 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 12:51:48,645 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 12:54:12,278 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 12:54:12,290 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 12:54:12,309 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 12:54:12,311 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 12:56:08,829 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 12:56:08,834 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 12:56:08,839 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 12:56:08,846 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 12:56:09,122 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 12:56:09,127 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:17:42,356 log Internal Server Error: /userprofile/login/
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: login() missing 1 required positional argument: 'user'
ERROR 2025-10-13 13:17:42,417 basehttp "GET /userprofile/login/ HTTP/1.1" 500 62115
ERROR 2025-10-13 13:23:34,058 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:23:34,060 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:23:36,428 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:23:36,435 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:23:36,442 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:23:36,442 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:23:37,213 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:23:37,216 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:23:37,218 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:23:37,219 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:24:08,627 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:24:08,628 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:24:08,631 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:24:08,631 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:24:58,124 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:24:58,143 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:24:58,192 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:24:58,200 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:24:58,399 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:24:58,400 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:24:58,404 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:24:58,405 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:25:08,661 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:25:08,669 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:25:08,681 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:25:08,691 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:25:14,248 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:25:14,285 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:25:14,303 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:25:14,306 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:25:14,344 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:25:14,347 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:25:17,551 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:25:17,573 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:25:17,590 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:25:17,593 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:25:17,615 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:25:17,619 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:25:17,620 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:25:17,622 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:26:03,174 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:26:03,177 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:26:03,200 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:26:03,221 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:26:04,020 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:26:04,023 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:26:04,059 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:26:04,066 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:26:04,068 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:26:04,072 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:26:04,814 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:26:04,818 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:26:04,821 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:26:04,829 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:26:08,672 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:26:08,679 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:26:08,680 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:26:08,686 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-13 13:50:51,774 log Internal Server Error: /userprofile/dashboard/
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\urls\base.py", line 81, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'logout'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\USER\Desktop\wealthnettrader\userprofile\views.py", line 255, in dashboard
    return render(request, 'userprofile/dashboard.html', {
        'user': user,
    ...<7 lines>...
        'profile_edit_form': profile_edit_form,
    })
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\urls\base.py", line 87, in reverse
    raise NoReverseMatch(
    ...<2 lines>...
    )
django.urls.exceptions.NoReverseMatch: 'logout' is not a registered namespace inside 'userprofile'
ERROR 2025-10-13 13:50:51,813 basehttp "GET /userprofile/dashboard/ HTTP/1.1" 500 143777
ERROR 2025-10-13 14:11:37,587 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\Desktop\wealthnettrader\home\views.py", line 4, in home_view
    return render(request, 'home/index.html')
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'investment' not found. 'investment' is not a valid view function or pattern name.
ERROR 2025-10-13 14:11:37,685 basehttp "GET / HTTP/1.1" 500 120127
ERROR 2025-10-13 15:39:47,781 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\Desktop\wealthnettrader\home\views.py", line 4, in home_view
    return render(request, 'home/index.html')
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
ERROR 2025-10-13 15:39:48,018 basehttp "GET / HTTP/1.1" 500 116173
ERROR 2025-10-13 15:53:16,304 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\Desktop\wealthnettrader\home\views.py", line 4, in home_view
    return render(request, 'home/index.html')
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'dasboard' not found. 'dasboard' is not a valid view function or pattern name.
ERROR 2025-10-13 15:53:16,314 basehttp "GET / HTTP/1.1" 500 121135
ERROR 2025-10-13 15:53:19,031 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\Desktop\wealthnettrader\home\views.py", line 4, in home_view
    return render(request, 'home/index.html')
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'dasboard' not found. 'dasboard' is not a valid view function or pattern name.
ERROR 2025-10-13 15:53:19,049 basehttp "GET / HTTP/1.1" 500 121148
ERROR 2025-10-13 15:53:22,062 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\Desktop\wealthnettrader\home\views.py", line 4, in home_view
    return render(request, 'home/index.html')
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'dasboard' not found. 'dasboard' is not a valid view function or pattern name.
ERROR 2025-10-13 15:53:22,074 basehttp "GET / HTTP/1.1" 500 120977
ERROR 2025-10-14 11:57:00,457 log Internal Server Error: /connectwallet/select-wallet/
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\wealthnettrader\connectwallet\views.py", line 53, in select_wallet
    send_mail(
    ~~~~~~~~~^
        subject=f"New Wallet Connected by {request.user.username}",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        fail_silently=False,
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\core\mail\__init__.py", line 92, in send_mail
    return mail.send()
           ~~~~~~~~~^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\core\mail\message.py", line 307, in send
    return self.get_connection(fail_silently).send_messages([self])
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\core\mail\backends\smtp.py", line 128, in send_messages
    new_conn_created = self.open()
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\core\mail\backends\smtp.py", line 86, in open
    self.connection = self.connection_class(
                      ~~~~~~~~~~~~~~~~~~~~~^
        self.host, self.port, **connection_params
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
                                    self.source_address)
                                    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\socket.py", line 864, in create_connection
    raise exceptions[0]
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\socket.py", line 849, in create_connection
    sock.connect(sa)
    ~~~~~~~~~~~~^^^^
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Desktop\wealthnettrader\connectwallet\views.py", line 75, in select_wallet
    return redirect('error_page', error_message=error_message)
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\shortcuts.py", line 51, in redirect
    resolve_url(to, *args, **kwargs),
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\shortcuts.py", line 184, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'error_page' with keyword arguments '{'error_message': 'Unexpected error occurred: [WinError 10061] No connection could be made because the target machine actively refused it'}' not found. 1 pattern(s) tried: ['connectwallet/error/\\Z']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\USER\Desktop\wealthnettrader\connectwallet\views.py", line 83, in select_wallet
    return redirect('error_page', error_message=error_message)
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\shortcuts.py", line 51, in redirect
    resolve_url(to, *args, **kwargs),
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\shortcuts.py", line 184, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\USER\Desktop\wealthnettrader\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'error_page' with keyword arguments '{'error_message': "Unexpected error occurred while saving wallet: Reverse for 'error_page' with keyword arguments '{'error_message': 'Unexpected error occurred: [WinError 10061] No connection could be made because the target machine actively refused it'}' not found. 1 pattern(s) tried: ['connectwallet/error/\\\\Z']"}' not found. 1 pattern(s) tried: ['connectwallet/error/\\Z']
ERROR 2025-10-14 11:57:00,688 basehttp "POST /connectwallet/select-wallet/ HTTP/1.1" 500 176624
